version: "3"

services:

  bn_mongodb:
    environment:
      MONGO_INITDB_DATABASE: towns_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    image: "mongo:latest"
    volumes:
      - ./mongodb_data:/data/towns_db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
    external: true