name: Makefile CI

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: make docker-build RELEASE=${{steps.release.outputs.version}}
      
    - name: Install dependencies
      run: make docker-push DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}, DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD}}, RELEASE=${{steps.release.outputs.version}}
