name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: make docker-run
      
    - name: Install dependencies
      run: make docker-push ${{ secrets.DOCKER_USERNAME }}, ${{ secrets.DOCKER_PASSWORD }}, {{ secrets.DOCKER_EMAIL }}
      

